// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/muhomorfus/lab1-template/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// PersonRepository is an autogenerated mock type for the personRepository type
type PersonRepository struct {
	mock.Mock
}

type PersonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PersonRepository) EXPECT() *PersonRepository_Expecter {
	return &PersonRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *PersonRepository) Create(ctx context.Context, _a1 models.Person) (int, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Person) (int, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Person) int); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Person) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PersonRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PersonRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 models.Person
func (_e *PersonRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *PersonRepository_Create_Call {
	return &PersonRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *PersonRepository_Create_Call) Run(run func(ctx context.Context, _a1 models.Person)) *PersonRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Person))
	})
	return _c
}

func (_c *PersonRepository_Create_Call) Return(_a0 int, _a1 error) *PersonRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PersonRepository_Create_Call) RunAndReturn(run func(context.Context, models.Person) (int, error)) *PersonRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PersonRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PersonRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PersonRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *PersonRepository_Expecter) Delete(ctx interface{}, id interface{}) *PersonRepository_Delete_Call {
	return &PersonRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PersonRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *PersonRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *PersonRepository_Delete_Call) Return(_a0 error) *PersonRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PersonRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *PersonRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *PersonRepository) Get(ctx context.Context, id int) (*models.Person, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Person, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Person); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PersonRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PersonRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *PersonRepository_Expecter) Get(ctx interface{}, id interface{}) *PersonRepository_Get_Call {
	return &PersonRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *PersonRepository_Get_Call) Run(run func(ctx context.Context, id int)) *PersonRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *PersonRepository_Get_Call) Return(_a0 *models.Person, _a1 error) *PersonRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PersonRepository_Get_Call) RunAndReturn(run func(context.Context, int) (*models.Person, error)) *PersonRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *PersonRepository) List(ctx context.Context) ([]models.Person, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Person, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Person); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PersonRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PersonRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PersonRepository_Expecter) List(ctx interface{}) *PersonRepository_List_Call {
	return &PersonRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *PersonRepository_List_Call) Run(run func(ctx context.Context)) *PersonRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PersonRepository_List_Call) Return(_a0 []models.Person, _a1 error) *PersonRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PersonRepository_List_Call) RunAndReturn(run func(context.Context) ([]models.Person, error)) *PersonRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *PersonRepository) Update(ctx context.Context, _a1 models.Person) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Person) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PersonRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PersonRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 models.Person
func (_e *PersonRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *PersonRepository_Update_Call {
	return &PersonRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *PersonRepository_Update_Call) Run(run func(ctx context.Context, _a1 models.Person)) *PersonRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Person))
	})
	return _c
}

func (_c *PersonRepository_Update_Call) Return(_a0 error) *PersonRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PersonRepository_Update_Call) RunAndReturn(run func(context.Context, models.Person) error) *PersonRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPersonRepository creates a new instance of PersonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonRepository {
	mock := &PersonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
