apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: {{ .Values.port }}
            - name: PGHOST
              value: {{ .Values.postgresql.host }}
            - name: PGPORT
              value: {{ .Values.postgresql.port }}
            - name: PGUSER
              value: {{ .Values.postgresql.user }}
            - name: PGPASSWORD
              value: {{ .Values.postgresql.password }}
            - name: PGDB
              value: {{ .Values.postgresql.db }}